In [1]:
import numpy as np
import pandas as pd

# Simulations == Monte Carlo Method
- Simulation is running an experiment
- Trial is the number of items in each experiment

## How to run a simulation with Python/Numpy/Pandas
1. Figure out a way to represent our data
2. Create a matrix of random data, rows = simulations, columns = trial
    - For example, rolling 2 dice 10,000 times means rows=10,000 and columns = 2 because we roll 2 dice each time.
3. Apply an aggregate function, row-wise to get the results of the simulation
4. Apply a final aggregate to get our probability

In [6]:
# Let's answer questions experimentally rather than theoretically
# What's the probability of flipping "Heads" on a coin?

# Let's flip a coin 100,000 times and figure out the probability of flipping "Heads"

# Let's find a way to represent out data
outcomes = ["Heads", "Tails"]
n_simulations = 1_000_000

flips = np.random.choice(outcomes,  size=n_simulations)
flips[0:5]

array(['Tails', 'Tails', 'Tails', 'Tails', 'Heads'], dtype='<U5')

In [7]:
# After flipping one million coins, our experiemental probability of flipping heads is:
(flips == "Heads").mean()

0.500013

In [17]:
# Another example: What is the probability of rolling a 5 on a 6 sided die?

# Step 1, represent our data's outcomes
outcomes = [1, 2, 3, 4, 5, 6]

# Step 2, create the data
n_simulations = 10_000

rolls = np.random.choice(outcomes, size=n_simulations)

# What are the chances we roll a 5?
(rolls == 5).mean()

0.1722

In [19]:
(rolls)[0:10]

array([1, 6, 2, 1, 1, 5, 1, 6, 4, 4])

In [18]:
(rolls == 5)[0:10]

array([False, False, False, False, False,  True, False, False, False,
       False])

In [21]:
# what's the probability of rolling a 5?
# sum up the count of times the roll was 5
# divide by the total number of rolls
number_of_fives_rolled = (rolls == 5).sum()
total_number_of_rolls = len(rolls)
number_of_fives_rolled / total_number_of_rolls

0.1722

In [23]:
(rolls == 5).mean()

0.1722

In [24]:
# What is the probability we'll roll a 5 or a 6 on a 6 sided die?
(rolls >= 5).mean()

0.3377

In [25]:
# What is the probabiliyt of rolling less than a 3 (but not including 3)
(rolls < 3).mean()

0.3287

In [26]:
# What are the chances we roll something other than 3
(rolls != 3).mean()

0.8335

## Let's Roll 2 Dice at Once!

1. Figure out a way to represent the data
2. Create a matrix of random data, rows=simulations, columns=trials
3. Apply an aggregagte row-wise to get the result of each simulation
4. Apply a final aggregate (probably the .mean) to get our probability

In [27]:
# What are the odds of rolling Snake Eyes on two dice?

# Step 1 Represent our outcomes
outcomes = [1, 2, 3, 4, 5, 6]

# Step 2: Create a matrix of random data where rows=simulations, columns=trial

# Simulation = the number of times we run the experiment
# Trials = the number of things in each experiment
n_simulations = 1_000_000
n_trials = 2 # b/c we're rolling 2 dice with each experiment

# size argument can set our simulation and trial size
rolls = np.random.choice(outcomes, size=(n_simulations, n_trials))
rolls.shape

(1000000, 2)

In [30]:
rolls[0:5]

array([[1, 3],
       [2, 5],
       [6, 5],
       [5, 5],
       [1, 3]])

In [29]:
# Step 3: Apply an aggregate row-wise
# axis=1 means sum across the rows
sum_of_rolls = rolls.sum(axis=1)
sum_of_rolls[0:5]

array([ 4,  7, 11, 10,  4])

In [ ]:
# Axis=0 means sum up the entire column. 
# If you don't put an axis, the default is 0
# rolls.sum(axis=0)

In [31]:
# Step 4.
# Add up all the times that an experiment produces the sum of 2
(sum_of_rolls == 2).mean()

0.027824

In [32]:
theoretical = 1/6 * 1/6
print(f"Our theoretical probability of rolling snake eyes is 1/6 * 1/6, which is {theoretical}")

Our theoretical probability of rolling snake eyes is 1/6 * 1/6, which is 0.027777777777777776


In [33]:
# What is the probability of rolling a 7 on two dice
# 1+6, 2+5, 3+4, 4+3, 5+2, 6+1

# step 1: represent our outcomes
outcomes = [1, 2, 3, 4, 5, 6]

# Step 2: generate a matrix of random outcomes, simulations = rows, trials = columns
# size=(simulations, trials)
# size=(experiements, number_of_dice per experiment)
rolls = np.random.choice(outcomes, size=(10_000, 2))
rolls[0:4]

array([[4, 1],
       [2, 4],
       [5, 2],
       [6, 6]])

In [34]:
# Step 3, apply a row-wise aggregate
# axis=1 to apply sum to rows
sum_of_rolls = rolls.sum(axis=1)
sum_of_rolls[0:4]

array([ 5,  6,  7, 12])

In [35]:
p = (sum_of_rolls == 7).mean()
print(f"The experimental probability of rolling a sum of 7 on two dice at once is {p}")

The experimental probability of rolling a sum of 7 on two dice at once is 0.1718


In [36]:
# What's the probability of rolling 2 pips on 2 dice
outcomes = [1, 2, 3, 4, 5, 6]
n_simulations = 10_000

die1 = np.random.choice(outcomes, size=n_simulations)
die2 = np.random.choice(outcomes, size=n_simulations)

# Each array here shares an index where index = simulation_number
die1[0:3], die2[0:3]

(array([2, 1, 3]), array([4, 2, 4]))

In [37]:
(die1 == 2)[0:10]

array([ True, False, False, False, False,  True,  True,  True, False,
       False])

In [38]:
(die2 == 2)[0:10]

array([False,  True, False, False, False, False,  True, False, False,
        True])

In [44]:
# ((die1 == 2) & (die2 == 2))[0:10]
d1_rolled_2 = die1 == 2
d2_rolled_2 = die2 == 2

# d1_rolled_2[0:5], d2_rolled_2[0:5]
both_rolled_2 = d1_rolled_2 & d2_rolled_2
both_rolled_2.mean()

0.0263

In [45]:
1/6 * 1/6

0.027777777777777776

In [47]:
# What are the experimental probabilities of rolling each sum
df = pd.DataFrame()

# possible sum outcomes from 2 dice
df["outcome"] = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

# write a lil' function that gets the probability
def get_prob(n):
    return (sum_of_rolls == n).mean()

get_prob(2)

0.0292

In [48]:
# set the probability to its own column
df["probability"] = df.outcome.apply(get_prob)

print("Sum outcome of rolling 2 dice and the probability of seeing that outcome")
df

Sum outcome of rolling 2 dice and the probability of seeing that outcome


outcome  probability
0         2       0.0292
1         3       0.0578
2         4       0.0814
3         5       0.1103
4         6       0.1360
5         7       0.1718
6         8       0.1399
7         9       0.1128
8        10       0.0805
9        11       0.0533
10       12       0.0270

## Setting our own probabilities

In [50]:
# Let's answer questions experimentally rather than theoretically
# What's the probability of flipping "Heads" on a coin?

# Let's flip a coin 100,000 times and figure out the probability of flipping "Heads"

# Let's find a way to represent out data
outcomes = ["Heads", "Tails"]

flips = np.random.choice(outcomes, size=(10_000, 1), p=[0.55, 0.45])

(flips == "Heads").mean()

0.5487

In [51]:
# what are the chances of flipping two heads in a row?
flips = np.random.choice(outcomes, size=(10_000, 2), p=[0.55, 0.45])


array([['Tails', 'Heads'],
       ['Heads', 'Heads'],
       ['Heads', 'Heads'],
       ['Heads', 'Heads'],
       ['Heads', 'Heads']], dtype='<U5')

In [52]:
# It'll be a bit easier to check for two heads if the head = 1 and tail is 0
# might as well turn a binary into a binary

# let's say Heads is 1 and Tails is 0
outcomes = [1, 0]
flips = np.random.choice(outcomes, size=(100_000, 2), p=[0.55, 0.45])
flips[0:4]

array([[1, 1],
       [0, 1],
       [1, 1],
       [1, 1]])

In [53]:
# axis=1 to sum across the rows, so we have as many sums as we had pairs of coin flips
num_of_heads = flips.sum(axis=1)
num_of_heads

array([2, 1, 2, ..., 2, 1, 1])

In [54]:
(num_of_heads == 2).mean()

0.30219

In [55]:
# theoretical probability of flipping 2 unfair coin heads in a row
0.55 * .55

0.30250000000000005

In [56]:
# What if this is a fair coin?
outcomes = [1, 0]
flips = np.random.choice(outcomes, size=(100_000, 2))
num_of_heads = flips.sum(axis=1)
(num_of_heads == 2).mean()

0.25127

In [57]:
# theoretical probability of flipping two heads in a row
.5 * .5

0.25

In [58]:
# Rolling two dice at a time, what is the probability of rolling an odd and then and even?

# Step 1 is represent the world in Pandas/Numpy 
first_die = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)
second_die = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)

first_die, second_die

(array([1, 3, 1, ..., 6, 2, 1]), array([4, 6, 2, ..., 4, 3, 2]))

In [59]:
# We need to represent the results of the first die as an array of booleans
first_die_is_odd = (first_die % 2 != 0)

In [60]:
second_die_is_even = (second_die % 2 == 0)

In [61]:
first_odd_second_even = (first_die_is_odd & second_die_is_even)
first_odd_second_even

array([ True,  True,  True, ..., False, False,  True])

In [62]:
first_odd_second_even.mean()

0.24926

In [63]:
# Theoretical probability
.5 * .5

0.25